"""Build the Windows packages from Linux by running the Windows toolchain in
Wine.

PyInstaller cannot cross-build, so this keeps a Wine prefix in .wine/
with a Windows Python (and Inno Setup, for the installer) and runs
build_windows.py in it. The first run downloads and installs those;
later runs reuse them.
"""

import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parents[1]
PREFIX = ROOT / ".wine"
PYTHON_VERSION = "3.12.10"
PYTHON_URL = (
    f"https://www.python.org/ftp/python/{PYTHON_VERSION}/"
    f"python-{PYTHON_VERSION}-amd64.exe"
)
PYTHON_DIR = r"C:\Python312"
INNO_URL = (
    "https://github.com/jrsoftware/issrc/releases/download/is-6_7_3/innosetup-6.7.3.exe"
)
INNO_ISCC = PREFIX / "drive_c" / "Program Files (x86)" / "Inno Setup 6" / "ISCC.exe"


def wine(*command: str, check: bool = True) -> None:
    environment = {
        **os.environ,
        "WINEPREFIX": str(PREFIX),
        "WINEARCH": "win64",
        "WINEDEBUG": "-all",
    }
    print("+ wine", " ".join(command), flush=True)
    # Windows Python fails with "Invalid handle" when stdin is closed or stdout is a
    # plain file, so give it a null stdin and a pipe that we relay ourselves.
    process = subprocess.Popen(
        ["wine", *command],
        cwd=ROOT,
        env=environment,
        stdin=subprocess.DEVNULL,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        errors="replace",
    )
    assert process.stdout is not None
    for line in process.stdout:
        print(line, end="", flush=True)
    code = process.wait()
    if check and code:
        raise subprocess.CalledProcessError(code, command)


def download(url: str, name: str) -> Path:
    target = Path(tempfile.mkdtemp()) / name
    print(f"Downloading {url}", flush=True)
    with urlopen(url, timeout=120) as response, target.open("wb") as handle:
        shutil.copyfileobj(response, handle)
    if target.suffix == ".exe" and target.read_bytes()[:2] != b"MZ":
        raise RuntimeError(f"{url} did not return a Windows executable")
    return target


def ensure_python() -> str:
    python = PREFIX / "drive_c" / "Python312" / "python.exe"
    if not python.is_file():
        installer = download(PYTHON_URL, "python-installer.exe")
        wine(
            str(installer),
            "/quiet",
            f"TargetDir={PYTHON_DIR}",
            "InstallAllUsers=0",
            "Include_launcher=0",
            "Include_test=0",
            "PrependPath=0",
        )
    if not python.is_file():
        raise SystemExit("Could not install Python in the Wine prefix.")
    # Wine 9 lacks CopyFile2, which shutil uses on Python 3.12; hiding it makes
    # shutil fall back to its portable copy.
    (python.parent / "Lib" / "site-packages" / "sitecustomize.py").write_text(
        "import _winapi\n"
        "if hasattr(_winapi, 'CopyFile2'):\n"
        "    del _winapi.CopyFile2\n",
        encoding="utf-8",
    )
    return PYTHON_DIR + r"\python.exe"


def ensure_inno_setup() -> None:
    if INNO_ISCC.is_file():
        return
    try:
        installer = download(INNO_URL, "innosetup.exe")
        wine(str(installer), "/VERYSILENT", "/SUPPRESSMSGBOXES", "/NORESTART", "/SP-")
    except Exception as error:  # the zip is still built without the installer
        print(f"Inno Setup was not installed ({error}); skipping the installer.")


def main() -> int:
    if shutil.which("wine") is None:
        raise SystemExit("Wine is required: sudo apt install wine64")
    # PyInstaller reuses these folders, and a Linux bundle left in them breaks the
    # Windows build; both are regenerated by every build anyway.
    for stale in (ROOT / "dist" / "KubeScope", ROOT / "build"):
        shutil.rmtree(stale, ignore_errors=True)
    python = ensure_python()
    ensure_inno_setup()
    wine(python, "-m", "pip", "install", "--upgrade", "pip")
    # the spec builds from src/, so install the dependencies only; pip's isolated
    # project build would not see the CopyFile2 workaround above
    wine(python, "-m", "pip", "install", "pyside6>=6.11.2", "pyinstaller>=6.22.3")
    wine(python, "tools/build_windows.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
